name: Build Electron App

on:
  workflow_dispatch:

  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npx electron-builder --publish never

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/Media Player Setup 1.0.0.exe

      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: MediaPlayer
      #     path: release/